set(VCPKG_ENV_PASSTHROUGH_UNTRACKED EMSCRIPTEN_ROOT EMSDK PATH)

set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Emscripten)

if(NOT DEFINED ENV{EMSCRIPTEN_ROOT})
   if(NOT DEFINED ENV{EMSDK})
      set(EMSCRIPTEN_ROOT "C:/emsdk/upstream/emscripten")
   else()
      set(EMSCRIPTEN_ROOT "$ENV{EMSDK}/upstream/emscripten")
   endif()
else()
   set(EMSCRIPTEN_ROOT "$ENV{EMSCRIPTEN_ROOT}")
endif()

set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${EMSCRIPTEN_ROOT}/cmake/Modules/Platform/Emscripten.cmake")

set(COMMON_FLAGS "-fexceptions -sSUPPORT_LONGJMP=emscripten -g0 -O3 -msimd128 -flto=thin")

set(VCPKG_C_FLAGS "${COMMON_FLAGS}")
set(VCPKG_CXX_FLAGS "${COMMON_FLAGS}")
set(VCPKG_C_FLAGS_DEBUG "${COMMON_FLAGS}")
set(VCPKG_CXX_FLAGS_DEBUG "${COMMON_FLAGS}")
set(VCPKG_C_FLAGS_RELEASE "${COMMON_FLAGS}")
set(VCPKG_CXX_FLAGS_RELEASE "${COMMON_FLAGS}")
