name: Build WASM Package

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install dependencies
        run: yarn install

      - name: Build WASM
        run: npm run build:wasm

      - name: Fix dist permissions
        run: sudo chown -R $(whoami):$(whoami) dist
    
      - name: Build TypeScript
        run: npm run build
    
      - name: Create package zip
        run: |
          zip -r wasm-image-optimization-build.zip package.json dist
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wasm-image-optimization-build
          path: wasm-image-optimization-build.zip
