name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VCPKG_ROOT: /usr/local/share/vcpkg
      VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/vcpkg_cache,readwrite"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'triplets/**') }}-${{ github.run_id }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'triplets/**') }}-
            vcpkg-${{ runner.os }}-

      - name: Install Ninja & ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build ccache

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-wasm

      - name: Cache Emscripten
        uses: actions/cache@v4
        with:
          path: emsdk-cache
          key: ${{ runner.os }}-emsdk-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-emsdk-

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: "emsdk-cache"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Cache Skia Source
        uses: actions/cache@v4
        with:
          path: external/skia
          key: skia-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            skia-

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Wasm Configure
        run: pnpm wasm:configure
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache
          CMAKE_CXX_COMPILER_LAUNCHER: ccache

      - name: Wasm Build
        run: pnpm wasm:build

      - name: ccache stats
        run: ccache -s

      - name: Build TS Packages
        run: pnpm run build:js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "packages/playground/out"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
